import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import { createServer } from 'http';
import { initializeSocket } from './socket';
import userRoutes from './routes/users';
import companyRoutes from './routes/companies';
import branchRoutes from './routes/branches';
import noteRoutes from './routes/notes';
import { prisma } from './lib/prisma';
import notelabels from './routes/notelabels';
import formSectionRoutes from './routes/formSections';
import formFieldRoutes from './routes/formFields';
import formPermissionRoutes from './routes/formPermissions';
import activityRoutes from './routes/activities';
import commentRoutes from './routes/comments';
import messageRoutes from './routes/messages';
import authRoutes from './routes/auth';
import todoRoutes from './routes/todos';
import settingsRoutes from './routes/settings';
import leadStageRoutes from './routes/leadStages';
import invoiceStageRoutes from './routes/invoiceStages';
import estimateStageRoutes from './routes/estimateStages';
import sourceRoutes from './routes/sources';
import contactTypeRoutes from './routes/contactTypes';
import salutationRoutes from './routes/salutations';
import callStatusRoutes from './routes/callStatuses';
import documentStageRoutes from './routes/documentStages';
import currencyRoutes from './routes/currencies';
import locationRoutes from './routes/locations';
import taxRoutes from './routes/taxes';
import unitRoutes from './routes/units';
import productPropertyRoutes from './routes/productProperties';
import dealPipelineRoutes from './routes/dealPipelines';
import userRoleRoutes from './routes/userRoles';
import accessControlRoutes from './routes/accessControls';
import securityRoutes from './routes/securities';
import permissionSettingRoutes from './routes/permissionSettings';
import businessProcessRoutes from './routes/businessProcesses';
import companyTypeRoutes from './routes/companyTypes';
import employeeRoutes from './routes/employees';
import industryRoutes from './routes/industries';
import dealTypeRoutes from './routes/dealTypes';
import emailTemplateRoutes from './routes/emailTemplates';
import smtpSettingRoutes from './routes/smtpSettings';
import emailNotificationRoutes from './routes/emailNotifications';
import emailSignatureRoutes from './routes/emailSignatures';
import formTemplateRoutes from './routes/formTemplates';
import customEntityPageRoutes from './routes/customEntityPages';
import entityRoutes from './routes/entities';
import feedRoutes from './routes/feed';
import notificationRoutes from './routes/notifications';
import collabRoutes from './routes/collabs';
import workGroupRoutes from './routes/workGroups';
import documentRoutes from './routes/documents';
import calendarEventRoutes from './routes/calendarEvents';
import fitnessRoutes from './routes/fitness';
import nutritionRoutes from './routes/nutrition';
import sleepRoutes from './routes/sleep';
import productRoutes from './routes/products';
import productCategoryRoutes from './routes/productCategories';
import productSubCategoryRoutes from './routes/productSubCategories';
import productImageUploadRoutes from './routes/productImageUpload';
import orderRoutes from './routes/orders';
import customerRoutes from './routes/customers';
import tableRoutes from './routes/tables';
import reportTemplateRoutes from './routes/reportTemplates';
import pdfReportRoutes from './routes/pdfReports';
import dealDashboardRoutes from './routes/dealDashboards';
import fileRoutes from './routes/files';
import folderRoutes from './routes/folders';
import uploadRoutes from './routes/upload';
import projectRoutes from './routes/projects';
import userConnectionRoutes from './routes/userConnections';
import subscriptionRoutes from './routes/subscriptions';
import menuItemRoutes from './routes/menuItems';
import pricingPlanRoutes from './routes/pricingPlans';
import chatRoutes from './routes/chats';
import chatMessageRoutes from './routes/chatMessages';
import chatAccessRoutes from './routes/chatAccess';
import callRoutes from './routes/calls';
import mailRoutes from './routes/mail';
import taskRoutes from './routes/tasks';
import customFieldRoutes from './routes/customFields';
import analyticalReportRoutes from './routes/analyticalReports';
import autoNumberingRoutes from './routes/autoNumbering';
import reminderRoutes from './routes/reminders';
import customerPaymentRoutes from './routes/customerPayments';
import supplierPaymentRoutes from './routes/supplierPayments';
import loginHistoryRoutes from './routes/loginHistory';
import driveUsageRoutes from './routes/driveUsage';
import systemSettingsRoutes from './routes/systemSettings';
import exceptionLogRoutes from './routes/exceptionLogs';
import path from 'path';
import { errorLoggerMiddleware } from './middleware/errorLogger';

const app = express();
const PORT = process.env.PORT || 5001;

app.use(cors());
app.use(express.json());

// Serve static files from the files directory
app.use('/files', express.static(path.join(process.cwd(), 'files')));
// Also serve from uploads directory for backward compatibility
app.use('/uploads', express.static(path.join(process.cwd(), 'uploads')));

// Routes
app.use('/users', userRoutes);
app.use('/companies', companyRoutes);
app.use('/branches', branchRoutes);
app.use('/notelabels', notelabels);
app.use('/notes', noteRoutes); // Use plural for consistency with frontend
app.use('/note', noteRoutes); // Keep singular as alias for backward compatibility
app.use('/todos', todoRoutes);
console.log('Todo routes registered at /todos');
app.use('/settings', settingsRoutes);
console.log('Settings routes registered at /settings');
app.use('/form-sections', formSectionRoutes);
app.use('/form-fields', formFieldRoutes);
app.use('/form-permissions', formPermissionRoutes);
app.use('/activities', activityRoutes);
app.use('/comments', commentRoutes);
app.use('/messages', messageRoutes);
app.use('/auth', authRoutes);
app.use('/lead-stages', leadStageRoutes);
app.use('/invoice-stages', invoiceStageRoutes);
app.use('/estimate-stages', estimateStageRoutes);
app.use('/sources', sourceRoutes);
app.use('/contact-types', contactTypeRoutes);
app.use('/salutations', salutationRoutes);
app.use('/call-statuses', callStatusRoutes);
app.use('/document-stages', documentStageRoutes);
app.use('/currencies', currencyRoutes);
app.use('/locations', locationRoutes);
app.use('/taxes', taxRoutes);
app.use('/units', unitRoutes);
app.use('/product-properties', productPropertyRoutes);
app.use('/deal-pipelines', dealPipelineRoutes);
app.use('/user-roles', userRoleRoutes);
app.use('/access-controls', accessControlRoutes);
app.use('/securities', securityRoutes);
app.use('/permission-settings', permissionSettingRoutes);
app.use('/business-processes', businessProcessRoutes);
app.use('/company-types', companyTypeRoutes);
app.use('/employees', employeeRoutes);
app.use('/industries', industryRoutes);
app.use('/deal-types', dealTypeRoutes);
app.use('/email-templates', emailTemplateRoutes);
app.use('/smtp-settings', smtpSettingRoutes);
app.use('/email-notifications', emailNotificationRoutes);
app.use('/email-signatures', emailSignatureRoutes);
app.use('/form-templates', formTemplateRoutes);
app.use('/custom-entity-pages', customEntityPageRoutes);
app.use('/entities', entityRoutes);
app.use('/feed', feedRoutes);
app.use('/notifications', notificationRoutes);
console.log('Notification routes registered at /notifications');
app.use('/collabs', collabRoutes);
console.log('Collab routes registered at /collabs');
app.use('/work-groups', workGroupRoutes);
console.log('Work group routes registered at /work-groups');
app.use('/documents', documentRoutes);
console.log('Document routes registered at /documents');
app.use('/calendar-events', calendarEventRoutes);
console.log('Calendar event routes registered at /calendar-events');
app.use('/fitness', fitnessRoutes);
console.log('Fitness routes registered at /fitness');
app.use('/nutrition', nutritionRoutes);
console.log('Nutrition routes registered at /nutrition');
app.use('/sleep', sleepRoutes);
console.log('Sleep routes registered at /sleep');
app.use('/products', productRoutes);
console.log('Product routes registered at /products');
app.use('/product-categories', productCategoryRoutes);
console.log('Product category routes registered at /product-categories');
app.use('/product-subcategories', productSubCategoryRoutes);
console.log('Product subcategory routes registered at /product-subcategories');
app.use('/product-images', productImageUploadRoutes);
console.log('Product image upload routes registered at /product-images');
app.use('/orders', orderRoutes);
console.log('Order routes registered at /orders');
app.use('/tables', tableRoutes);
console.log('Table routes registered at /tables');
app.use('/report-templates', reportTemplateRoutes);
console.log('Report template routes registered at /report-templates');
app.use('/pdf-reports', pdfReportRoutes);
console.log('PDF report routes registered at /pdf-reports');
app.use('/deal-dashboards', dealDashboardRoutes);
console.log('Deal dashboard routes registered at /deal-dashboards');
app.use('/customers', customerRoutes);
console.log('Customer routes registered at /customers');
app.use('/files', fileRoutes);
console.log('File routes registered at /files');
app.use('/folders', folderRoutes);
console.log('Folder routes registered at /folders');
app.use('/upload', uploadRoutes);
console.log('Upload routes registered at /upload');
app.use('/projects', projectRoutes);
console.log('Project routes registered at /projects');
app.use('/', userConnectionRoutes);
console.log('User connection routes registered');
app.use('/subscriptions', subscriptionRoutes);
console.log('Subscription routes registered at /subscriptions');
app.use('/menu-items', menuItemRoutes);
console.log('Menu item routes registered at /menu-items');
app.use('/pricing-plans', pricingPlanRoutes);
console.log('Pricing plan routes registered at /pricing-plans');
app.use('/chats', chatRoutes);
console.log('Chat routes registered at /chats');
app.use('/chat-messages', chatMessageRoutes);
console.log('Chat message routes registered at /chat-messages');
app.use('/chat-access', chatAccessRoutes);
console.log('Chat access routes registered at /chat-access');
app.use('/calls', callRoutes);
console.log('Call routes registered at /calls');
app.use('/mail', mailRoutes);
console.log('Mail routes registered at /mail');
app.use('/tasks', taskRoutes);
console.log('Task routes registered at /tasks');
app.use('/custom-fields', customFieldRoutes);
console.log('Custom field routes registered at /custom-fields');
app.use('/analytical-reports', analyticalReportRoutes);
console.log('Analytical report routes registered at /analytical-reports');
app.use('/auto-numbering', autoNumberingRoutes);
app.use('/reminders', reminderRoutes);
console.log('Reminder routes registered at /reminders');
console.log('Auto-numbering routes registered at /auto-numbering');
app.use('/customer-payments', customerPaymentRoutes);
console.log('Customer payment routes registered at /customer-payments');
app.use('/supplier-payments', supplierPaymentRoutes);
console.log('Supplier payment routes registered at /supplier-payments');
app.use('/login-history', loginHistoryRoutes);
console.log('Login history routes registered at /login-history');
app.use('/drive-usage', driveUsageRoutes);
console.log('Drive usage routes registered at /drive-usage');
app.use('/system-settings', systemSettingsRoutes);
console.log('System settings routes registered at /system-settings');
app.use('/exception-logs', exceptionLogRoutes);
console.log('Exception logs routes registered at /exception-logs');

// Serve static files from uploads directory
app.use('/uploads', express.static('uploads'));

// Error logger (must be after routes)
app.use(errorLoggerMiddleware);

// Create HTTP server
const httpServer = createServer(app);

// Initialize Socket.io
initializeSocket(httpServer);

// Start server
httpServer.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
  console.log(`Socket.io server initialized`);
});

process.on('SIGINT', async () => {
  await prisma.$disconnect();
  process.exit(0);
});